# Análisis numérico con Python

Diego Fernando Marin

# Numpy

[NumPy](https://numpy.org/) proporciona una forma eficiente de manipular arreglos multi-dimensionales en Python. Sus características más importantes son:
- Ofrece la estructura ``ndarray``, que permite trabajar con vectores, matrices y arreglos multi-dimensionales en forma eficiente (memoria y procesamiento)
- Provee una sintaxis legible y eficiente para trabajar con dichos datos, desde operadores aritméticos básicos que operan a nivel del elemento, hasta operaciones algebraicas complejas.
- A diferencia de las listas, los elementos en un arreglo de Numpy deben tener todos el mismo tipo.

In [5]:
# la forma convencional de importan la librería/Modulo Numpy
import numpy as np
np.__version__

'1.20.1'

En su uso más básico, los arreglos Numpy se parecen mucho a las listas. Por ejemplo, compare la creación de este arreglo con los números del 1 al 20, con su lista equivalente.

In [2]:
# Listas básicas de Python
lista = list(range(1, 21))
print(lista)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [4]:
# Arreglo (o Vector) de Numpy
arreglo = np.arange(1, 21)
print(type(arreglo), arreglo)

<class 'numpy.ndarray'> [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


Pero la sintaxis de Numpy para manipular los datos en un arreglo es más elegante que el lenguaje Python básico.

Por ejemplo, para crear una lista con todos los números de otra lista elevados al cuadrado:

In [5]:
# Usando List-comprehension
lista2 = [ numero**2 for numero in lista ]
print(lista2)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400]


In [6]:
# Los operados de Numpy se aplican a cada elemento del arreglo
arreglo2 = arreglo ** 2
print(arreglo2)

[  1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289 324
 361 400]


In [7]:
# Las listas están limitadas de una dimensión, los arreglos de Numpy pueden ser multi-dimensionales:
matriz = arreglo.reshape(4,5)
print(matriz)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [9]:
# Todos los elementos de un arreglo deben ser del mismo tipo
reales = np.array([5, 3.14, 8, -2, 6.626, 4, 1, 0.5, 9])
print(reales)

[ 5.     3.14   8.    -2.     6.626  4.     1.     0.5    9.   ]


In [10]:
# Es posible crear arreglos usando list-comprehension
m2 = np.array( [ range(i, i + 7, 3) for i in [3, 7, 11, 15, 19] ] )
print(m2)

[[ 3  6  9]
 [ 7 10 13]
 [11 14 17]
 [15 18 21]
 [19 22 25]]


Numpy ofrece muchos métodos para crear arreglos en forma eficiente:

In [12]:
# Crear un arreglo de tamaño 20, lleno de ceros
ceros = np.zeros(20, dtype=int)
print(ceros)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [13]:
# Crear una matriz 3x5, llena de unos
m0 = np.ones((3, 5), dtype=float)
print(m0)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
# Crear una matriz 2x2x2, llena de 3.14
pi2 = np.full((2, 2, 2), 3.14)
print(pi2)

[[[3.14 3.14]
  [3.14 3.14]]

 [[3.14 3.14]
  [3.14 3.14]]]


In [17]:
# Crear un arreglo de 15 números igualmente espaciados entre 0 y 1
l1 = np.linspace(0, 1, 14)
print(l1)

[0.         0.07692308 0.15384615 0.23076923 0.30769231 0.38461538
 0.46153846 0.53846154 0.61538462 0.69230769 0.76923077 0.84615385
 0.92307692 1.        ]


In [21]:
# Crear una matriz 3x4 con números aleatorios uniformemente distribuidos, entre 0 y 1:
m2 = np.random.random((4, 3))
print(m2)

[[0.56130379 0.4981039  0.07415283]
 [0.57689876 0.67331888 0.14264795]
 [0.30887329 0.53348879 0.86152364]
 [0.17020763 0.69518455 0.05395963]]


In [20]:
# Crear un arreglo de 15 valores normalmente distribuido, con media 0 y desviación estándar 1
na = np.random.normal(0, 1, 15)
print(na)

[-1.43302065  1.24318307  1.53555446  0.09766475  0.05644614  0.7439005
  0.14334498  2.76362671 -0.64020473 -0.56708276  0.08058753  0.45103499
 -1.28162583  1.58163916  2.07594141]


In [6]:
# Crear una matriz de 7x3 valores aleatorios entre 0 y 100
m3 = np.random.randint(0, 100, (7, 3))
print(m3)

[[66 39 91]
 [61 92 63]
 [20 68 81]
 [65 37 19]
 [76 98 13]
 [80 40 15]
 [95 21 11]]


In [23]:
# Crear una matriz identidad de 5x5
i1 = np.eye(5)
print(i1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Un arreglo Numpy tiene un conjunto de atributos que resultan útiles:

In [24]:
print("m3 ndim: ", m3.ndim)
print("m3 shape:", m3.shape)
print("m3 size: ", m3.size)
print("m3.dtype:", m3.dtype)
print("m3.itemsize:", m3.itemsize, "bytes")
print("m3.nbytes:", m3.nbytes, "bytes")

m3 ndim:  2
m3 shape: (7, 3)
m3 size:  21
m3.dtype: int64
m3.itemsize: 8 bytes
m3.nbytes: 168 bytes


Los elementos de un arreglos se acceden de la misma forma que en una lista; `[0]` para el primero, `[-1]`para el último, `[4]`para el 5to. 

In [25]:
a = np.linspace(0, np.pi, 5)
print(a)

[0.         0.78539816 1.57079633 2.35619449 3.14159265]


In [26]:
print(f"a[0] = {a[0]}")
print(f"a[-1] = {a[-1]}")
print(f"a[4] = {a[4]}")

a[0] = 0.0
a[-1] = 3.141592653589793
a[4] = 3.141592653589793


In [27]:
x = np.array([[1, 2, 4, 10], [7, 6, 8, 8], [1, 6, 7, 7]])
print(x)

[[ 1  2  4 10]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [28]:
print(f"x[0,0] = {x[0, 0]}")
print(f"x[2,0] = {x[2, 0]}")
print(f"x[2,-1] = {x[2, -1]}")

x[0,0] = 1
x[2,0] = 1
x[2,-1] = 7


Numpy también ofrece una gran cantidad de operaciones, optimizadas para trabajar con arreglos.

In [29]:
# Trigonométricas
print(f"sin(a) = {np.sin(a)}")
print(f"cos(a) = {np.cos(a)}")
print(f"tan(a) = {np.tan(a)}")

sin(a) = [0.00000000e+00 7.07106781e-01 1.00000000e+00 7.07106781e-01
 1.22464680e-16]
cos(a) = [ 1.00000000e+00  7.07106781e-01  6.12323400e-17 -7.07106781e-01
 -1.00000000e+00]
tan(a) = [ 0.00000000e+00  1.00000000e+00  1.63312394e+16 -1.00000000e+00
 -1.22464680e-16]


In [30]:
# Exponencial y Logaritmos
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(3, x))

e^x = [[2.71828183e+00 7.38905610e+00 5.45981500e+01 2.20264658e+04]
 [1.09663316e+03 4.03428793e+02 2.98095799e+03 2.98095799e+03]
 [2.71828183e+00 4.03428793e+02 1.09663316e+03 1.09663316e+03]]
2^x = [[   2.    4.   16. 1024.]
 [ 128.   64.  256.  256.]
 [   2.   64.  128.  128.]]
3^x = [[    3     9    81 59049]
 [ 2187   729  6561  6561]
 [    3   729  2187  2187]]


In [31]:
print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))

ln(x) = [[0.         0.69314718 1.38629436 2.30258509]
 [1.94591015 1.79175947 2.07944154 2.07944154]
 [0.         1.79175947 1.94591015 1.94591015]]
log2(x) = [[0.         1.         2.         3.32192809]
 [2.80735492 2.5849625  3.         3.        ]
 [0.         2.5849625  2.80735492 2.80735492]]
log10(x) = [[0.         0.30103    0.60205999 1.        ]
 [0.84509804 0.77815125 0.90308999 0.90308999]
 [0.         0.77815125 0.84509804 0.84509804]]


## Operaciones con matrices

In [32]:
# Crear dos matrices con valores iniciales
x = np.array([[1, 2], [4, 5]])
y = np.array([[7, 8], [9, 10]])
print("x =\n", x)
print("y =\n", y)

x =
 [[1 2]
 [4 5]]
y =
 [[ 7  8]
 [ 9 10]]


In [33]:
# Suma los elementos de ambas matrices
print("x + y =\n", x + y)

x + y =
 [[ 8 10]
 [13 15]]


In [34]:
# Multiplica los elementos de ambas matrices (no multiplica matrices)
print("x * y =\n", x * y)

x * y =
 [[ 7 16]
 [36 50]]


In [35]:
# Producto de matrices, es equivalente a np.dot(x, y) 
print("x @ y =\n", x @ y)

x @ y =
 [[25 28]
 [73 82]]


In [36]:
print("suma de todos los elementos de x =\n", np.sum(x))

suma de todos los elementos de x =
 12


In [37]:
print("suma por columnas de y =\n", np.sum(y, axis=0))

suma por columnas de y =
 [16 18]


In [38]:
print("suma por filas de y =\n", np.sum(y, axis=1))

suma por filas de y =
 [15 19]


In [39]:
print("matriz traspuesta de x =\n", x.T)

matriz traspuesta de x =
 [[1 4]
 [2 5]]


In [9]:
# Crear dos matrices 3x2 con números aleatorios
a = np.floor( 10 * np.random.random((3,2)) )
b = np.floor( 10 * np.random.random((3,2)) )
print("a =\n", a)
print("b =\n", b)

a =
 [[0. 0.]
 [5. 0.]
 [2. 1.]]
b =
 [[0. 7.]
 [2. 9.]
 [1. 0.]]


In [41]:
# Apilar en forma vertical
np.vstack((a,b))

array([[5., 0.],
       [9., 0.],
       [5., 5.],
       [7., 7.],
       [6., 3.],
       [8., 4.]])

In [10]:
# Apilar en forma horizontal
np.hstack((a,b))

array([[0., 0., 0., 7.],
       [5., 0., 2., 9.],
       [2., 1., 1., 0.]])

# Manipulación de imágenes con Numpy

![Tiburon](Tiburon.jpg)

In [19]:
# Manipulación de imágenes
from PIL import Image

In [20]:
# Se lee la imagen y se convierte en arreglo
tiburon = np.array(Image.open('Tiburon.jpg'))

In [16]:
print(tiburon.ndim)
print(tiburon.shape)
print(tiburon.size)
tiburon

3
(413, 770, 3)
954030


array([[[ 49, 104, 134],
        [ 46, 101, 131],
        [ 46, 101, 131],
        ...,
        [136, 171, 211],
        [126, 157, 185],
        [127, 158, 186]],

       [[ 53, 109, 136],
        [ 49, 104, 134],
        [ 48, 103, 133],
        ...,
        [112, 151, 190],
        [117, 152, 180],
        [124, 159, 187]],

       [[ 60, 117, 144],
        [ 55, 112, 139],
        [ 51, 108, 135],
        ...,
        [ 75, 121, 157],
        [ 88, 132, 161],
        [102, 146, 175]],

       ...,

       [[ 16,  55,  54],
        [  2,  41,  40],
        [  0,  36,  36],
        ...,
        [  0,  71,  83],
        [  0,  68,  81],
        [  6,  74,  87]],

       [[ 18,  57,  56],
        [  3,  42,  41],
        [  0,  38,  37],
        ...,
        [  0,  71,  85],
        [  1,  69,  80],
        [  7,  75,  86]],

       [[ 17,  56,  53],
        [  2,  41,  38],
        [  0,  37,  34],
        ...,
        [  0,  70,  85],
        [  2,  68,  80],
        [  8,  74,  86]]

In [21]:
print(tiburon[50,80])

[ 48 104 139]
